name: parse_template
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Service Locator
  get_it: ^7.7.0

  # Navigation
  auto_route: ^8.2.0

  # Data
  parse_server_sdk_flutter: ^8.0.0
  shared_preferences: ^2.2.3
  sembast: ^3.7.1+2
  sembast_web: ^2.4.0+2
  dio: ^5.4.3+1

  # State Management
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1

  # System
  path: ^1.9.0
  path_provider: ^2.1.3

  # Utility
  xxtea: ^2.1.0
  talker_flutter: ^4.2.4
  flutter_native_splash: ^2.4.0
  icons_launcher: ^2.1.7

  # Google services
  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.1
  flutter_local_notifications: ^17.1.2

dev_dependencies:
  # Debug & Testing
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # Code generation
  build_runner: ^2.4.11

  # Navigation
  auto_route_generator: ^8.0.0

  # State management
  mobx_codegen: ^2.6.1

flutter:
  uses-material-design: true


flutter_native_splash:
  color: "#ffffff"
  branding: assets/application/app_icon.png
  color_dark: "#313542"

  android_12:
    color: "#ffffff"
    icon_background_color: "#313542"
    color_dark: "#313542"

  android: true
  ios: true

icons_launcher:
  platforms:
    android:
      enable: true
      image_path: "assets/application/app_icon.png"
    ios:
      enable: true
      image_path: "assets/application/app_icon_ios.png"
