// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDBBLPhgVMfOOFrHy5jjCJqA_nNpSxiKU',
    appId: '1:255073582082:web:3d2b01c36dffa617a63b1b',
    messagingSenderId: '255073582082',
    projectId: 'basketball-609e9',
    authDomain: 'basketball-609e9.firebaseapp.com',
    storageBucket: 'basketball-609e9.appspot.com',
    measurementId: 'G-JBHX243MBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGspvTYXHorhLhSclEWSj7IccGpgsLf2M',
    appId: '1:255073582082:android:6034bf9f442406a4a63b1b',
    messagingSenderId: '255073582082',
    projectId: 'basketball-609e9',
    storageBucket: 'basketball-609e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5VMYMuxJzK_Cql1mAcJg3JGRMjyh4JD0',
    appId: '1:255073582082:ios:fd0bb8e9d3c7a0a6a63b1b',
    messagingSenderId: '255073582082',
    projectId: 'basketball-609e9',
    storageBucket: 'basketball-609e9.appspot.com',
    iosBundleId: 'com.aksahypa.parseTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5VMYMuxJzK_Cql1mAcJg3JGRMjyh4JD0',
    appId: '1:255073582082:ios:fd0bb8e9d3c7a0a6a63b1b',
    messagingSenderId: '255073582082',
    projectId: 'basketball-609e9',
    storageBucket: 'basketball-609e9.appspot.com',
    iosBundleId: 'com.aksahypa.parseTemplate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDBBLPhgVMfOOFrHy5jjCJqA_nNpSxiKU',
    appId: '1:255073582082:web:a5c283de2e6f1651a63b1b',
    messagingSenderId: '255073582082',
    projectId: 'basketball-609e9',
    authDomain: 'basketball-609e9.firebaseapp.com',
    storageBucket: 'basketball-609e9.appspot.com',
    measurementId: 'G-VFCV6RRHS8',
  );
}
